### PR TITLE
Fix deleting stale clusters when importing clusters

### LINKED ISSUE #62: Cluster importer fails to delete stale clusters
The calls to `delete_all` fails because `delete_all` [here](https://github.com/dm-drogeriemarkt/foreman_wreckingball/blob/master/app/services/foreman_wreckingball/vmware_cluster_importer.rb#L20) only tries to delete only those records and not the associations. So as a result if the have some facets for example, then it will fail with a foreign_key_constraint exception. `destroy_all` should be used here as this will destroy the child records accordingly.

### PR DESCRIPTION
**Pull request by kamils-iRonin**
fix #62

### CODE REVIEW

**Comment by kamils-iRonin** [comment]
[test foreman_wreckingball]

File: app/services/foreman_wreckingball/vmware_cluster_importer.rb [hunk 1]
```diff
@@ -20,9 +20,9 @@ def import!
     def delete_removed_clusters
       delete_query = ::ForemanWreckingball::VmwareCluster.where(:compute_resource => compute_resource).where.not(:name => cluster_names)
       counters[:deleted] = if ActiveRecord::Base.connection.adapter_name.downcase.starts_with? 'mysql'
-                             ::ForemanWreckingball::VmwareCluster.where(:id => delete_query.pluck(:id)).delete_all
```
Comment (timogoebel) [inline app/services/foreman_wreckingball/vmware_cluster_importer.rb]: `delete_all` was used here to generate a single `DELETE FROM` sql query. I don't think we need to distinguish between mysql and other DBMS because `destroy_all` will use a query per record.

Comment (timogoebel) [reply app/services/foreman_wreckingball/vmware_cluster_importer.rb]: I would remove the if condition and just call `delete_query.destroy_all` in every case.

Comment (leewaa) [reply app/services/foreman_wreckingball/vmware_cluster_importer.rb]: AH I see! Thanks
